[general]
  live_config_reload = true
  import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
  ]

[window]
  startup_mode = "Maximized"

[mouse]
  hide_when_typing = true

[keyboard]
  bindings = [
    {key = "-", mods = "Control", action = "DecreaseFontSize"},
    {key = "+", mods = "Control", action = "IncreaseFontSize"},
    {key = "0", mods = "Control", action = "ResetFontSize"},
  ]

[font]
  normal = {family = "SauceCodePro Nerd Font", style = "Regular"}
  size = 16
  offset = {x = 0, y = 5}
