[general]
  live_config_reload = true
  import = [
    "~/.config/alacritty/themes/themes/catppuccin-mocha.toml"
  ]

[window]
  startup_mode = "Maximized"
  opacity = 0.9

[mouse]
  hide_when_typing = true

[keyboard]
  bindings = [
    {key = "-", mods = "Control", action = "DecreaseFontSize"},
    {key = "+", mods = "Control", action = "IncreaseFontSize"},
    {key = "0", mods = "Control", action = "ResetFontSize"},
  ]

[font]
  normal = {family = "Jetbrains Mono Nerd Font", style = "Regular"}
  size = 16
  offset = {x = 0, y = 0}

[env]
  TERM = "xterm-256color"
